# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_created_by_field_removed'),
    ]

    database_operations = [
        migrations.AlterModelTable('TimelineEvent', 'timeline_timelineevent')
    ]

    state_operations = [
        migrations.DeleteModel('TimelineEvent')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
