# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_auto_20170814_1146'),
    ]

    operations = [
        migrations.RenameModel('Package', 'Project')
    ]
