# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_move_timelineevent_model_to_timeline_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approval_request_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
