# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_project_approval_request_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('', '----'), ('UNKNOWN', 'Unknown'), ('LIVE_RELEASED', 'Live/Released'), ('WORKINGPROTOTYPE_BETA', 'Working Prototype/Beta'), ('DEMO_ALPHA', 'Demo/Alpha'), ('CONCEPT', 'Concept'), ('ABANDONED_BROKEN', 'Abandoned/Broken'), ('OUTOFDATE_RETIRED', 'Out of Date/Retired')], default='', help_text='<ul><li><strong>Live/Released</strong> - Project is ready to use</li><li><strong>Working Prototype/Beta</strong> - Project is working however, it still can contain some bugs</li><li><strong>Demo/Alpha</strong> - Project can be used by people which are not afraid of bugs and has very high pain threshold</li><li><strong>Concept</strong> - Project which pretends to be a working product</li><li><strong>Abandoned/Broken</strong> - Project is no longer available or it is completely broken</li><li><strong>Out of Date/Retired</strong> - Project is no longer needed, because of changes in ecosystem</li></ul>', max_length=100, verbose_name='Status'),
        ),
    ]
