# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_project_approval_request_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(blank=True, null=True, unique=True, verbose_name='Social URL')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
