# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_projectsociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsociallink',
            name='type',
            field=models.CharField(choices=[('', '----'), ('TWITTER', 'Unknown'), ('FACEBOOK', 'Facebook'), ('TELEGRAM', 'Telegram'), ('REDDIT', 'Reddit'), ('MEDIUM', 'Medium'), ('YOUTUBE', 'YouTube')], default='', max_length=16),
        ),
    ]
