# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-03 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_auto_20180316_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImageUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.CharField(max_length=256, verbose_name='Url')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagesUrl', to='package.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
