# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_projectsociallink_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsociallink',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sociallinks', to='package.Project'),
        ),
        migrations.AlterField(
            model_name='projectsociallink',
            name='type',
            field=models.CharField(choices=[('', '----'), ('TWITTER', 'Twitter'), ('FACEBOOK', 'Facebook'), ('TELEGRAM', 'Telegram'), ('REDDIT', 'Reddit'), ('MEDIUM', 'Medium'), ('YOUTUBE', 'YouTube')], default='', max_length=16),
        ),
    ]
