# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0008_auto_20170814_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title2'),
        ),
    ]
