# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0008_auto_20180309_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsociallink',
            name='url',
            field=models.URLField(default='', verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='projectsociallink',
            unique_together=set([('url', 'project')]),
        ),
    ]
