# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0009_project_title2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title2',
            field=models.URLField(blank=True, help_text='Link to place, where project was announced for the first time', null=True, verbose_name='Title2'),
        ),
    ]
