# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0010_auto_20170815_0327'),
    ]

    operations = [
        migrations.RenameField('Project', 'title2', 'announcement_post'),
    ]
