# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_auto_20170815_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project URL'),
        ),
    ]
