# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0013_auto_20170815_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, help_text='Enter your project repo hosting URL here. Example: https://github.com/opencomparison/opencomparison', null=True, unique=True, verbose_name='repo URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title'),
        ),
    ]
