# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0017_auto_20170816_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='announcement_post',
            field=models.URLField(blank=True, help_text='Link to place, where project was announced for the first time', null=True, verbose_name='Announcement Post'),
        ),
    ]
