# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0018_auto_20170816_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_github',
            field=models.BooleanField(default=False, verbose_name='Show Github stats'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='show_pypi',
        ),
    ]
