# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 23:57
from __future__ import unicode_literals

from django.db import migrations


def slug(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    Project = apps.get_model('package', 'Project')
    for project in Project.objects.all():
        if project.slug.endswith("-1") and not Project.objects.filter(slug=project.slug[:-2]).exists():
            project.slug = project.slug[:-2]
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0020_auto_20170831_2329'),
    ]

    operations = [
        migrations.RunPython(slug),
    ]
