# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 01:40
from __future__ import unicode_literals

from django.db import migrations, models


def unknown_status(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    Project = apps.get_model('package', 'Project')
    for project in Project.objects.all():
        project.status = 'UNKNOWN'
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0021_auto_20170831_2357'),
    ]

    operations = [
        migrations.RunPython(unknown_status),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('LIVE_RELEASED', 'Live/Released'), ('WORKINGPROTOTYPE_BETA', 'Working Prototype/Beta'), ('DEMO_ALPHA', 'Demo/Alpha'), ('CONCEPT', 'Concept'), ('ABANDONED_BROKEN', 'Abandoned/Broken'), ('OUTOFDATE_RETIRED', 'Out of Date/Retired')], default='UNKNOWN', help_text='Live/Released - Project is ready to use\nWorking Prototype/Beta - Project is working however, it still can contain some bugs\nDemo/Alpha - Project can be used by people which are not afraid of bugs and has very high pain threshold\nConcept - Something that pretends to be a working project\nAbandoned/Broken - Project is no longer available or it is completely broken\nOut of Date/Retired - Project is no longer needed, because of changes in ecosystem', max_length=100, verbose_name='Status'),
        ),
    ]
