# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_steemit_chat_account'),
        ('package', '0024_auto_20170901_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, to='profiles.Profile'),
        ),
    ]
