# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-02 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_steemit_chat_account'),
        ('package', '0026_auto_20170901_1059'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together=set([('profile', 'project')]),
        ),
    ]
