# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0028_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_img_proj', to='package.ProjectImage'),
        ),
    ]
