# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0029_project_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('LIVE_RELEASED', 'Live/Released'), ('WORKINGPROTOTYPE_BETA', 'Working Prototype/Beta'), ('DEMO_ALPHA', 'Demo/Alpha'), ('CONCEPT', 'Concept'), ('ABANDONED_BROKEN', 'Abandoned/Broken'), ('OUTOFDATE_RETIRED', 'Out of Date/Retired')], default='UNKNOWN', help_text='\n            <ul>\n                <li>Live/Released - Project is ready to use</li>\n                <li>Working Prototype/Beta - Project is working however, it still can contain some bugs</li>\n                <li>Demo/Alpha - Project can be used by people which are not afraid of bugs and has very high pain threshold</li>\n                <li>Concept - Something that pretends to be a working project</li>\n                <li>Abandoned/Broken - Project is no longer available or it is completely broken</li>\n                <li>Out of Date/Retired - Project is no longer needed, because of changes in ecosystem</li>\n            </ul>\n            ', max_length=100, verbose_name='Status'),
        ),
    ]
