# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0030_auto_20170905_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='role_confirmed',
            field=models.BooleanField(default=False, verbose_name='Role confirmed by team mate'),
        ),
    ]
