# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0031_teammembership_role_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='package.Project'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
