# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 09:14
from __future__ import unicode_literals

import core.fields
from django.db import migrations
import package.models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0032_auto_20170926_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='img',
            field=core.fields.SizeAndContentTypeRestrictedImageField(default='None/no-img.jpg', upload_to=package.models.project_img_path),
        ),
    ]
