# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0033_auto_20170926_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, help_text='Enter your project repo hosting URL here. Example: https://github.com/opencomparison/opencomparison', null=True, unique=True, verbose_name='Repository URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('', '----'), ('UNKNOWN', 'Unknown'), ('LIVE_RELEASED', 'Live/Released'), ('WORKINGPROTOTYPE_BETA', 'Working Prototype/Beta'), ('DEMO_ALPHA', 'Demo/Alpha'), ('CONCEPT', 'Concept'), ('ABANDONED_BROKEN', 'Abandoned/Broken'), ('OUTOFDATE_RETIRED', 'Out of Date/Retired')], default='', help_text='\n            <ul>\n                <li><strong>Live/Released</strong> - Project is ready to use</li>\n                <li><strong>Working Prototype/Beta</strong> - Project is working however, it still can contain some bugs</li>\n                <li><strong>Demo/Alpha</strong> - Project can be used by people which are not afraid of bugs and has very high pain threshold</li>\n                <li><strong>Concept</strong> - Something that pretends to be a working project</li>\n                <li><strong>Abandoned/Broken</strong> - Project is no longer available or it is completely broken</li>\n                <li><strong>Out of Date/Retired</strong> - Project is no longer needed, because of changes in ecosystem</li>\n            </ul>\n            ', max_length=100, verbose_name='Status'),
        ),
    ]
