# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0034_auto_20170929_0836'),
    ]

    operations = [
        migrations.RenameField('Project', 'title', 'name'),
    ]
