# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20171011_1132'),
        ('package', '0036_auto_20171011_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Account'),
        ),
    ]
