# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20171011_1245'),
        ('package', '0037_teammembership_account'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together=set([('account', 'project')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_member_of', through='package.TeamMembership', to='profiles.Account'),
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='profile',
        ),
    ]
