# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_false_to_none(apps, schema_editor):
    #  We can't import the Person model directly as it may be a newer
    #  version than this migration expects. We use the historical version.

    TeamMembership = apps.get_model('package', 'TeamMembership')
    for tm in TeamMembership.objects.all():
        tm.role_confirmed = None
        tm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20171011_1245'),
        ('package', '0037_teammembership_account'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together=set([('account', 'project')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_member_of', through='package.TeamMembership',
                                         to='profiles.Account'),
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contributors',
        ),
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contribiuted_to', to='profiles.Account'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='role_confirmed',
            field=models.NullBooleanField(default=None, verbose_name='Role confirmed by team mate'),
        ),
        migrations.RunPython(migrate_false_to_none),
        migrations.AddField(
            model_name='teammembership',
            name='confirmed_by_project_owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='approvers', to='profiles.Account'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='project_owner',
            field=models.BooleanField(default=False, verbose_name='Project owner'),
        ),
        migrations.RenameField(
            model_name='teammembership',
            old_name="role_confirmed",
            new_name="role_confirmed_by_account"
        )
    ]
