# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0038_role_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='announcement_post',
            field=models.URLField(blank=True, help_text='Link to place, where project was announced for the first time', null=True, verbose_name='Announcement Post URL'),
        ),
    ]
