# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0039_auto_20171023_1403'),
    ]

    operations = [
        migrations.RenameField('Project', 'added_by', 'draft_added_by'),
        migrations.AlterField(
            model_name='project',
            name='draft_added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='drafted_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='approvers',
            field=models.ManyToManyField(blank=True, related_name='approved_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='is_awaiting_approval',
            field=models.BooleanField(default=False, null=None),
        ),
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=False, null=None),
        ),
    ]
