# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-12 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20171011_1245'),
        ('package', '0039_remove_project_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contribiuted_to', to='profiles.Account'),
        ),
    ]
