# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 12:49
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0039_auto_20171023_1403'),
    ]

    operations = [
        migrations.RenameField('Project', 'added_by', 'draft_added_by'),
        migrations.AlterField(
            model_name='project',
            name='draft_added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='drafted_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='published_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
