# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0040_auto_20171112_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='publication_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Publication time'),
        ),
    ]
