# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0040_rename_added_by2draft_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_awaiting_approval',
            field=models.BooleanField(default=False, null=None),
        ),
    ]
