# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 22:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0041_project_is_awaiting_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='published_by',
        ),
        migrations.AddField(
            model_name='project',
            name='approvers',
            field=models.ManyToManyField(blank=True, related_name='approved_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
