# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 22:59
from __future__ import unicode_literals

from django.db import migrations


def all_projects_awaiting_approval(apps, schema_editor):

    Project = apps.get_model('package', 'Project')
    for project in Project.objects.all():
        project.is_awaiting_approval = True
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0041_project_publication_time'),
    ]

    operations = [
        migrations.RunPython(all_projects_awaiting_approval),
    ]
