# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0042_auto_20171111_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=False, null=None),
        ),
    ]
