# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0042_auto_20171112_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
