# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0043_project_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='is_awaiting_for_approval',
            new_name='is_awaiting_approval',
        ),
    ]
