# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0043_project_contact_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contact_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Contact URL'),
        ),
    ]
