# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170814_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='steem_account',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Steem account'),
        ),
    ]
