# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170814_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='steemit_chat_account',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Steemit.chat account'),
        ),
    ]
