# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_steemit_chat_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifier_of', to='profiles.Profile'),
        ),
    ]
