# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_account_confirmed',
            field=models.BooleanField(default=False, verbose_name='Github account confirmed'),
        ),
        migrations.AddField(
            model_name='profile',
            name='steem_account_confirmed',
            field=models.BooleanField(default=False, verbose_name='Steem account confirmed'),
        ),
        migrations.AddField(
            model_name='profile',
            name='steemit_chat_account_confirmed',
            field=models.BooleanField(default=False, verbose_name='Steemit.chat account confirmed'),
        ),
    ]
