# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_profiles_to_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bitbucket_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github_account',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github_account_confirmed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='google_code_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='steem_account',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='steem_account_confirmed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='steemit_chat_account',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='steemit_chat_account_confirmed',
        ),
    ]
