# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0006_partial'),
        ('profiles', '0013_auto_20171011_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='account',
            name='user_social_auth',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth'),
        ),
    ]
