# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


def predefine_account_types_and_migrate_data(apps, schema_editor):
    #  We can't import the Person model directly as it may be a newer
    #  version than this migration expects. We use the historical version.
    Account = apps.get_model('profiles', 'Account')
    AccountType = apps.get_model('profiles', 'AccountType')

    type_steem = AccountType.objects.create(
        name="Steem",
        link_to_account_with_param="https://steemit.com/@{account_name}",
        link_to_avatar_with_params="https://img.steemconnect.com/@{account_name}?s={size}",
    )

    type_github = AccountType.objects.create(
        name="Github",
        link_to_account_with_param="https://github.com/@{account_name}",
        link_to_avatar_with_params="https://github.com/{account_name}.png?size={size}",
    )

    for account in Account.objects.all():
        if account.type == "GITHUB":
            account.account_type = type_github
        elif account.type == "STEEM":
            account.account_type = type_steem

        account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20171013_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=40)),
                ('link_to_account_with_param', models.CharField(max_length=256)),
                ('link_to_avatar_with_params', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.AccountType'),
        ),
        migrations.RunPython(predefine_account_types_and_migrate_data),
    ]
