# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20171013_1735'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('name', 'account_type')]),
        ),
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
    ]
