# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 18:08
from __future__ import unicode_literals

from django.db import migrations, models


def init_display_name(apps, schema_editor):
    #  We can't import the Person model directly as it may be a newer
    #  version than this migration expects. We use the historical version.
    AccountType = apps.get_model('profiles', 'AccountType')

    for type in AccountType.objects.all():
        type.display_name = type.name
        type.name = type.name.upper()
        type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20171013_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='display_name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.RunPython(init_display_name),
    ]
