# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0001_initial'),
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Project'),
        ),
        migrations.AddField(
            model_name='grid',
            name='packages',
            field=models.ManyToManyField(through='grid.GridPackage', to='package.Project'),
        ),
        migrations.AddField(
            model_name='feature',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.Grid'),
        ),
        migrations.AddField(
            model_name='element',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.Feature'),
        ),
        migrations.AddField(
            model_name='element',
            name='grid_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.GridPackage'),
        ),
    ]
