# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_auto_20171119_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Is Draft'),
        ),
    ]
