# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineeventinserterrulebook',
            name='last',
        ),
    ]
