# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 09:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial_squashed_0011_auto_20180227_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineeventinserterrulebook',
            name='last',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
