# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20180303_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='ruleset',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeline.TimelineEventInserterRulebook'),
        ),
    ]
