# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_move_timelineevent_model_to_timeline_app'),
        ('timeline', '0004_timelineevent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timelineevent',
            unique_together=set([('name', 'url', 'date', 'project')]),
        ),
        migrations.AlterModelTable(
            name='timelineevent',
            table=None,
        ),
    ]
