# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_auto_20180212_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineeventinserterrulebook',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timelineeventinserterrulebook',
            name='service_type',
            field=models.CharField(choices=[('SteemPostService', 'new post is published on Steem'), ('GithubReleaseService', 'new release is published on Github')], max_length=64),
        ),
    ]
