# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_auto_20180213_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineeventinserterrule',
            name='type',
            field=models.CharField(choices=[('SteemAuthorTimelineEventRule', 'Published by'), ('SteemTagTimelineEventRule', 'Has a tag'), ('SteemAfterDatetimeTimelineEventRule', 'Published after'), ('SteemTitleRegexpTimelineEventRule', 'Title regexp'), ('SteemTitlePrefixTimelineEventRule', 'Title prefix')], max_length=64),
        ),
    ]
