# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('timeline', '0007_auto_20180216_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='added_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='ruleset',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timeline.TimelineEventInserterRulebook'),
        ),
    ]
