# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_auto_20180216_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineeventinserterrulebook',
            name='name',
        ),
        migrations.AlterField(
            model_name='timelineeventinserterrule',
            name='type',
            field=models.CharField(choices=[('SteemAuthorTimelineEventRule', 'Published by'), ('SteemTagTimelineEventRule', 'Has a tag'), ('SteemAfterDatetimeTimelineEventRule', 'Published after'), ('SteemTitleRegexpTimelineEventRule', 'Title regexp'), ('SteemTitlePrefixTimelineEventRule', 'Title prefix'), ('GithubRepositoryTimelineEventRule', 'In repository')], max_length=64),
        ),
    ]
