# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0009_auto_20180217_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineeventinserterrule',
            name='type',
            field=models.CharField(choices=[('SteemAuthorTimelineEventRule', 'Published by'), ('SteemTagTimelineEventRule', 'Has a tag'), ('SteemAfterDatetimeTimelineEventRule', 'Published after'), ('SteemTitleRegexpTimelineEventRule', 'Title regexp'), ('SteemTitlePrefixTimelineEventRule', 'Title prefix')], max_length=64),
        ),
        migrations.AlterField(
            model_name='timelineeventinserterrulebook',
            name='service_type',
            field=models.CharField(choices=[('SteemPostService', 'new post is published on Steem')], max_length=64),
        ),
    ]
