# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettercache',
            name='last_time_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
