# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20180219_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercache',
            name='subscribes',
            field=models.BooleanField(default=False),
        ),
    ]
