# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0003_created_by_field_removed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEventInserterRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AuthorTimelineEventRule', 'AuthorTimelineEventRule')], max_length=64)),
                ('argument', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEventInserterRulebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_block_synchronized', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Project')),
            ],
        ),
        migrations.AddField(
            model_name='timelineeventinserterrule',
            name='rulebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline_event_inserter.TimelineEventInserterRulebook'),
        ),
    ]
