# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('weight', models.IntegerField(default=0, verbose_name='Weight')),
                ('item_type', models.CharField(choices=[('package', 'Package'), ('draft', 'Draft'), ('grid', 'Grid')], max_length=40, verbose_name='Item Type')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
                ('title_no_prefix', models.CharField(db_index=True, max_length=100, verbose_name='No Prefix Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('slug_no_prefix', models.SlugField(verbose_name='No Prefix Slug')),
                ('clean_title', models.CharField(db_index=True, max_length=100, verbose_name='Clean title with no crud')),
                ('description', models.TextField(blank=True, verbose_name='Repo Description')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Category')),
                ('absolute_url', models.CharField(max_length=255, verbose_name='Absolute URL')),
                ('repo_watchers', models.IntegerField(default=0, verbose_name='Stars')),
                ('repo_forks', models.IntegerField(default=0, verbose_name='repo forks')),
                ('pypi_downloads', models.IntegerField(default=0, verbose_name='Pypi downloads')),
                ('usage', models.IntegerField(default=0, verbose_name='Number of users')),
                ('participants', models.TextField(blank=True, help_text='List of collaborats/participants on the project', verbose_name='Participants')),
                ('last_committed', models.DateTimeField(blank=True, null=True, verbose_name='Last commit')),
                ('last_released', models.DateTimeField(blank=True, null=True, verbose_name='Last release')),
            ],
            options={
                'verbose_name_plural': 'SearchV2s',
                'ordering': ['-weight'],
            },
        ),
    ]
