# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 06:38
from __future__ import unicode_literals

from django.db import migrations, models


def clear_searchv2(apps, schema_editor):
    SearchV2 = apps.get_model('searchv2', 'SearchV2')
    SearchV2.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('searchv2', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_searchv2),
        migrations.AddField(
            model_name='searchv2',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Is draft'),
        ),
        migrations.AddField(
            model_name='searchv2',
            name='item_id',
            field=models.IntegerField(default=0, verbose_name='Item ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchv2',
            name='item_type',
            field=models.CharField(choices=[('package', 'Package'), ('grid', 'Grid')], max_length=40, verbose_name='Item Type'),
        ),
        migrations.AlterUniqueTogether(
            name='searchv2',
            unique_together=set([('item_type', 'item_id')]),
        ),
    ]
